package gdr.eznote.frames;

import gdr.eznote.configuration.EzNoteConfigurator;
import gdr.eznote.document.EzNoteChangeValidator;
import gdr.eznote.document.EzNoteTXT;
import gdr.eznote.exceptions.BadValidationException;
import gdr.eznote.exceptions.FileSelectionException;
import gdr.eznote.util.EzNoteFrameUtil;
import gdr.eznote.listeners.EzNoteWindowAdapter;
import gdr.eznote.themes.EzNoteTheme;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JTextArea;
import javax.swing.UIManager;

/**
 * Main Editor frame
 * @author GDR
 */
public class EzNoteFrame extends javax.swing.JFrame {

    private EzNoteFileChooser fc;
    private EzNoteFrameUtil util;
    public EzNoteTXT document;
    private EzNoteWindowAdapter wlis;
    
    private EzNoteFrameAbout winAbout;
    private EzNoteFrameSettings winAppr;
    
    private EzNoteConfigurator conf;
    
    /**
     * Constructor and manual components init
     */
    public EzNoteFrame(EzNoteConfigurator conf) {
        initComponents();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text Files", "txt", "text");
        this.fc = new EzNoteFileChooser(this, "test");
        this.fc.setFileFilter(filter);
        this.winAbout = new EzNoteFrameAbout(this);
        this.winAbout.dispose();
        this.winAppr = new EzNoteFrameSettings(this);
        this.winAppr.dispose();
        this.util = new EzNoteFrameUtil(this);
        this.wlis = new EzNoteWindowAdapter(this);
        this.conf = conf;
        editorPane.setViewportView(getEditor());
        this.setDocumentListener(document);
        this.addWindowListener(wlis);
    }

    /**
     * Set the document listener of the window
     * @param dc EzNoteDocumentListener
     */
    
    public void setDocumentListener(EzNoteTXT dc) {
        this.editor.getDocument().addDocumentListener(dc);
    }

    /**
     * Returns the frame utilities class
     * @return EzNoteFrameUtil
     */
    public EzNoteFrameUtil getUtilities() {
        return this.util;
    }
    
    public EzNoteConfigurator getConfigurator() {
        return this.conf;
    }

    /**
     * Returns the filechooser of the window
     * @return EzNoteFileChooser
     */
    public EzNoteFileChooser getFileChooser() {
        return this.fc;
    }

    /**
     * Returns the document of the window
     * @return EzNoteDocument
     */
    public EzNoteTXT getDocument() {
        return this.document;
    }
    
    public void setDocument(File f){
        this.document = new EzNoteTXT(this, EzNoteFrameUtil.getProperFileExtension(f));
    }

    /**
     * Returns the filename of the current document
     * @return String filename of the current document
     */
    public String getFilename() {
        return this.document.file.getName();
    }

    /**
     * Returns the Editor component
     * @return JTextArea of the main frame
     */
    public JTextArea getEditor() {
        return this.editor;
    }

    @Deprecated
    public void themeApply(EzNoteTheme theme){
        paintThemeToFrame(theme);
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        toolbarMain = new javax.swing.JToolBar();
        toolNew = new javax.swing.JButton();
        sepr1 = new javax.swing.JToolBar.Separator();
        toolOpen = new javax.swing.JButton();
        toolQSave = new javax.swing.JButton();
        toolSaveAs = new javax.swing.JButton();
        sepr2 = new javax.swing.JToolBar.Separator();
        toolbarAbout = new javax.swing.JToolBar();
        buttonEzNote = new javax.swing.JButton();
        editorPane = new javax.swing.JScrollPane();
        editor = new javax.swing.JTextArea();
        toolbarBottom = new javax.swing.JToolBar();
        label1 = new javax.swing.JLabel();
        dispCaretX = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        dispCaretY = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jLabel2 = new javax.swing.JLabel();
        dispRows = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        dispLetters = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        buttonNew = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        buttonOpen = new javax.swing.JMenuItem();
        buttonQSave = new javax.swing.JMenuItem();
        buttonSaveAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        buttonExit = new javax.swing.JMenuItem();
        menuSettings = new javax.swing.JMenu();
        buttonAppearance = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(540, 300));

        toolbarMain.setBackground(new java.awt.Color(204, 204, 204));
        toolbarMain.setBorder(null);
        toolbarMain.setFloatable(false);
        toolbarMain.setForeground(new java.awt.Color(0, 0, 0));
        toolbarMain.setBorderPainted(false);
        toolbarMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        toolbarMain.setMaximumSize(new java.awt.Dimension(1000000, 36));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, toolbarMain, org.jdesktop.beansbinding.ELProperty.create("${preferredSize}"), toolbarMain, org.jdesktop.beansbinding.BeanProperty.create("minimumSize"));
        bindingGroup.addBinding(binding);

        toolNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_newfile.png"))); // NOI18N
        toolNew.setToolTipText("New");
        toolNew.setBorderPainted(false);
        toolNew.setFocusable(false);
        toolNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolNew.setMaximumSize(new java.awt.Dimension(28, 28));
        toolNew.setMinimumSize(new java.awt.Dimension(28, 28));
        toolNew.setPreferredSize(new java.awt.Dimension(28, 28));
        toolNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolNewActionPerformed(evt);
            }
        });
        toolbarMain.add(toolNew);
        toolbarMain.add(sepr1);

        toolOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_openfile.png"))); // NOI18N
        toolOpen.setToolTipText("Open...");
        toolOpen.setBorderPainted(false);
        toolOpen.setFocusable(false);
        toolOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolOpen.setMaximumSize(new java.awt.Dimension(28, 28));
        toolOpen.setMinimumSize(new java.awt.Dimension(28, 28));
        toolOpen.setPreferredSize(new java.awt.Dimension(28, 28));
        toolOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolOpenActionPerformed(evt);
            }
        });
        toolbarMain.add(toolOpen);

        toolQSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_savefile.png"))); // NOI18N
        toolQSave.setToolTipText("Save");
        toolQSave.setBorderPainted(false);
        toolQSave.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_savefile_disabled.png"))); // NOI18N
        toolQSave.setEnabled(false);
        toolQSave.setFocusable(false);
        toolQSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolQSave.setMaximumSize(new java.awt.Dimension(28, 28));
        toolQSave.setMinimumSize(new java.awt.Dimension(28, 28));
        toolQSave.setPreferredSize(new java.awt.Dimension(28, 28));
        toolQSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolQSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolQSaveActionPerformed(evt);
            }
        });
        toolbarMain.add(toolQSave);

        toolSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_saveasfile.png"))); // NOI18N
        toolSaveAs.setToolTipText("Save As...");
        toolSaveAs.setBorderPainted(false);
        toolSaveAs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        toolSaveAs.setFocusable(false);
        toolSaveAs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolSaveAs.setMaximumSize(new java.awt.Dimension(28, 28));
        toolSaveAs.setMinimumSize(new java.awt.Dimension(28, 28));
        toolSaveAs.setPreferredSize(new java.awt.Dimension(28, 28));
        toolSaveAs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolSaveAsActionPerformed(evt);
            }
        });
        toolbarMain.add(toolSaveAs);
        toolbarMain.add(sepr2);

        toolbarAbout.setFloatable(false);
        toolbarAbout.setRollover(true);
        toolbarAbout.setBorderPainted(false);
        toolbarAbout.setFocusable(false);
        toolbarAbout.setMaximumSize(new java.awt.Dimension(63, 36));
        toolbarAbout.setMinimumSize(new java.awt.Dimension(63, 36));
        toolbarAbout.setPreferredSize(new java.awt.Dimension(100, 36));

        buttonEzNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_about.png"))); // NOI18N
        buttonEzNote.setToolTipText("About EzNote");
        buttonEzNote.setBorderPainted(false);
        buttonEzNote.setFocusable(false);
        buttonEzNote.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        buttonEzNote.setMaximumSize(new java.awt.Dimension(28, 28));
        buttonEzNote.setMinimumSize(new java.awt.Dimension(28, 28));
        buttonEzNote.setPreferredSize(new java.awt.Dimension(28, 28));
        buttonEzNote.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonEzNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEzNoteActionPerformed(evt);
            }
        });
        toolbarAbout.add(buttonEzNote);

        editor.setColumns(20);
        editor.setRows(5);
        editorPane.setViewportView(editor);

        toolbarBottom.setFloatable(false);
        toolbarBottom.setRollover(true);

        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText(" P: ");
        label1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        toolbarBottom.add(label1);

        dispCaretX.setForeground(new java.awt.Color(255, 255, 255));
        dispCaretX.setText("*");
        dispCaretX.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        toolbarBottom.add(dispCaretX);

        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText(":");
        label3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        toolbarBottom.add(label3);

        dispCaretY.setForeground(new java.awt.Color(255, 255, 255));
        dispCaretY.setText("*");
        dispCaretY.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        toolbarBottom.add(dispCaretY);
        toolbarBottom.add(jSeparator3);

        jLabel2.setText("R: ");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        toolbarBottom.add(jLabel2);

        dispRows.setText("*");
        dispRows.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        toolbarBottom.add(dispRows);
        toolbarBottom.add(jSeparator5);

        jLabel3.setText("Cl: ");
        toolbarBottom.add(jLabel3);

        jLabel4.setText("*");
        toolbarBottom.add(jLabel4);
        toolbarBottom.add(jSeparator6);

        jLabel1.setText("C: ");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        toolbarBottom.add(jLabel1);

        dispLetters.setText("*");
        dispLetters.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        toolbarBottom.add(dispLetters);
        toolbarBottom.add(jSeparator7);

        jLabel5.setText("Ch: ");
        toolbarBottom.add(jLabel5);

        jLabel6.setText("0");
        toolbarBottom.add(jLabel6);

        menuFile.setMnemonic('f');
        menuFile.setText("File");

        buttonNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        buttonNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_newfile.png"))); // NOI18N
        buttonNew.setText("New");
        buttonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewActionPerformed(evt);
            }
        });
        menuFile.add(buttonNew);
        menuFile.add(jSeparator2);

        buttonOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        buttonOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_openfile.png"))); // NOI18N
        buttonOpen.setText("Open");
        buttonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenActionPerformed(evt);
            }
        });
        menuFile.add(buttonOpen);

        buttonQSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        buttonQSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_savefile.png"))); // NOI18N
        buttonQSave.setText("Save");
        buttonQSave.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_savefile_disabled.png"))); // NOI18N
        buttonQSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQSaveActionPerformed(evt);
            }
        });
        menuFile.add(buttonQSave);

        buttonSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_saveasfile.png"))); // NOI18N
        buttonSaveAs.setText("Save As...");
        buttonSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveAsActionPerformed(evt);
            }
        });
        menuFile.add(buttonSaveAs);
        menuFile.add(jSeparator1);

        buttonExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        buttonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_exit.png"))); // NOI18N
        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        menuFile.add(buttonExit);

        menuBar.add(menuFile);

        menuSettings.setMnemonic('p');
        menuSettings.setText("Preferences");

        buttonAppearance.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        buttonAppearance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_settings.png"))); // NOI18N
        buttonAppearance.setText("Settings");
        buttonAppearance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAppearanceActionPerformed(evt);
            }
        });
        menuSettings.add(buttonAppearance);

        menuBar.add(menuSettings);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolbarAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(toolbarMain, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE))
            .addComponent(editorPane)
            .addComponent(toolbarBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toolbarMain, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toolbarAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(editorPane, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(toolbarBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveAsActionPerformed
        try {
            EzNoteChangeValidator.validateAction(this.document, EzNoteChangeValidator.FILE_SAVEAS);
        } catch (BadValidationException ex) {
            ex.printStackTrace();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (FileSelectionException ex) {
            Logger.getLogger(EzNoteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonSaveAsActionPerformed

    private void buttonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenActionPerformed
        try {
            EzNoteChangeValidator.validateAction(this.document, EzNoteChangeValidator.FILE_OPEN);
        } catch (BadValidationException ex) {
            ex.printStackTrace();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (FileSelectionException ex) {
            Logger.getLogger(EzNoteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonOpenActionPerformed

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
        boolean isValid = false;
        try {
            isValid = EzNoteChangeValidator.validateAction(this.document, EzNoteChangeValidator.FILE_NEW);
        } catch (BadValidationException ex) {
            ex.printStackTrace();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (FileSelectionException ex) {
            Logger.getLogger(EzNoteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (isValid) {
            this.newFile();
        }
    }//GEN-LAST:event_buttonNewActionPerformed

    private void buttonQSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQSaveActionPerformed
        try {
            EzNoteChangeValidator.validateAction(this.document, EzNoteChangeValidator.FILE_QSAVE);
        } catch (BadValidationException ex) {
            ex.printStackTrace();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (FileSelectionException ex) {
            Logger.getLogger(EzNoteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonQSaveActionPerformed

    private void toolNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolNewActionPerformed
        boolean isValid = false;
        try {
            isValid = EzNoteChangeValidator.validateAction(this.document, EzNoteChangeValidator.FILE_NEW);
        } catch (BadValidationException ex) {
            ex.printStackTrace();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (FileSelectionException ex) {
            Logger.getLogger(EzNoteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (isValid) {
            this.newFile();
        }
    }//GEN-LAST:event_toolNewActionPerformed

    private void toolQSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolQSaveActionPerformed
        try {
            EzNoteChangeValidator.validateAction(this.document, EzNoteChangeValidator.FILE_QSAVE);
        } catch (BadValidationException ex) {
            ex.printStackTrace();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (FileSelectionException ex) {
            Logger.getLogger(EzNoteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_toolQSaveActionPerformed

    private void toolSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolSaveAsActionPerformed
        try {
            EzNoteChangeValidator.validateAction(this.document, EzNoteChangeValidator.FILE_SAVEAS);
        } catch (BadValidationException ex) {
            ex.printStackTrace();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (FileSelectionException ex) {
            Logger.getLogger(EzNoteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_toolSaveAsActionPerformed

    private void toolOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolOpenActionPerformed
        try {
            EzNoteChangeValidator.validateAction(this.document, EzNoteChangeValidator.FILE_OPEN);
        } catch (BadValidationException ex) {
            ex.printStackTrace();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (FileSelectionException ex) {
            Logger.getLogger(EzNoteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_toolOpenActionPerformed

    private void buttonEzNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEzNoteActionPerformed
        this.winAbout.setLocationRelativeTo(this);
        this.winAbout.setVisible(true);
    }//GEN-LAST:event_buttonEzNoteActionPerformed

    private void buttonAppearanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAppearanceActionPerformed
        this.winAppr.resetLockState();
        if(this.getConfigurator().getConfigurationThemeMode()==1){
            this.winAppr.changeThemeLockState(1);
        }
        this.winAppr.setLocationRelativeTo(this);
        this.winAppr.setVisible(true);
    }//GEN-LAST:event_buttonAppearanceActionPerformed
    
    /**
     * Initialize a new file while the program is starting, and locks the quick
     * save buttons
     */
    public void initializeStartup() {
        this.newFile();
        this.disableSaveButtons();
    }

    /**
     * Enables save buttons
     * @deprecated Will not support disabled buttons anymore
     */
    @Deprecated
    public void enableSaveButtons() {
        this.buttonQSave.setEnabled(true);
        this.toolQSave.setEnabled(true);
    }

    /**
     * Disables save buttons
     * @deprecated Will not support disabled buttons anymore
     */
    @Deprecated
    public void disableSaveButtons() {
        this.buttonQSave.setEnabled(false);
        this.toolQSave.setEnabled(false);
    }

    ////ACTIONS
    private void newFile() {
        this.editor.setText("");
        this.setTitle(this.util.getWindowTitle(false, "Untitled"));
        this.document = new EzNoteTXT(this, new File("temp/tmp.txt"));
        this.document.updateWindowTitle();
    }
    //////


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem buttonAppearance;
    private javax.swing.JMenuItem buttonExit;
    private javax.swing.JButton buttonEzNote;
    private javax.swing.JMenuItem buttonNew;
    private javax.swing.JMenuItem buttonOpen;
    private javax.swing.JMenuItem buttonQSave;
    private javax.swing.JMenuItem buttonSaveAs;
    public javax.swing.JLabel dispCaretX;
    public javax.swing.JLabel dispCaretY;
    private javax.swing.JLabel dispLetters;
    private javax.swing.JLabel dispRows;
    private javax.swing.JTextArea editor;
    private javax.swing.JScrollPane editorPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuSettings;
    private javax.swing.JToolBar.Separator sepr1;
    private javax.swing.JToolBar.Separator sepr2;
    private javax.swing.JButton toolNew;
    private javax.swing.JButton toolOpen;
    private javax.swing.JButton toolQSave;
    private javax.swing.JButton toolSaveAs;
    private javax.swing.JToolBar toolbarAbout;
    private javax.swing.JToolBar toolbarBottom;
    private javax.swing.JToolBar toolbarMain;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public void paintThemeToFrame(EzNoteTheme theme) {
        if("javax.swing.plaf.metal.MetalLookAndFeel".equals(UIManager.getCrossPlatformLookAndFeelClassName())){
            this.editor.setBorder(null);
            this.toolbarMain.setBorder(null);
            this.toolbarAbout.setBorder(null);
            this.toolbarBottom.setBorder(null);
        }
        System.out.println(UIManager.getCrossPlatformLookAndFeelClassName());
        //editor color
        this.editor.setBackground(theme.getEditorColor().getColor());
        //editor caret and font color
        this.editor.setCaretColor(theme.getCaretColor().getColor());
        this.editor.setForeground(theme.getFontColor().getColor());
        //menu bar colors (DISABLED BECAUSE OF WINDOWS LAF
        //this.menuBar.setBackground(theme.getToolbarColor().getColor());
        //this.menuFile.setForeground(theme.getToolbarColor().getTextColor());
        //this.menuSettings.setForeground(theme.getToolbarColor().getTextColor());
        //toolbars colors
        this.toolbarAbout.setBackground(theme.getToolbarColor().getColor());
        this.toolbarMain.setBackground(theme.getToolbarColor().getColor());
        this.toolbarBottom.setBackground(theme.getToolbarColor().getColor());
        //toolbar components color
        this.buttonEzNote.setBackground(theme.getToolbarColor().getColor());
        this.toolNew.setBackground(theme.getToolbarColor().getColor());
        this.toolQSave.setBackground(theme.getToolbarColor().getColor());
        this.toolSaveAs.setBackground(theme.getToolbarColor().getColor());
        this.toolOpen.setBackground(theme.getToolbarColor().getColor());
        //bottom bar components colors
        this.label1.setForeground(theme.getToolbarColor().getTextColor());
        this.dispCaretX.setForeground(theme.getToolbarColor().getTextColor());
        this.label3.setForeground(theme.getToolbarColor().getTextColor());
        this.dispCaretY.setForeground(theme.getToolbarColor().getTextColor());
        this.jLabel1.setForeground(theme.getToolbarColor().getTextColor());
        this.dispLetters.setForeground(theme.getToolbarColor().getTextColor());
        this.jLabel2.setForeground(theme.getToolbarColor().getTextColor());
        this.dispRows.setForeground(theme.getToolbarColor().getTextColor());
        this.jLabel3.setForeground(theme.getToolbarColor().getTextColor());
        this.jLabel4.setForeground(theme.getToolbarColor().getTextColor());
    }

}
