package gdr.eznote.frames;

import gdr.eznote.configuration.EzNoteConfigurator;
import gdr.eznote.document.EzNoteChangeValidator;
import gdr.eznote.document.EzNoteDocument;
import gdr.eznote.exceptions.BadValidationException;
import gdr.eznote.frames.EzNoteFileChooser;
import gdr.eznote.frames.EzNoteFrameAbout;
import gdr.eznote.frames.EzNoteFrameAppearance;
import gdr.eznote.util.EzNoteFrameUtil;
import gdr.eznote.listeners.EzNoteWindowAdapter;
import gdr.eznote.themes.EzNoteTheme;
import java.io.FileNotFoundException;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JTextArea;

/**
 * Main Editor frame
 * @author GDR
 */
public class EzNoteFrame extends javax.swing.JFrame {

    private EzNoteFileChooser fc;
    private EzNoteFrameUtil util;
    private EzNoteDocument doc;
    private EzNoteWindowAdapter wlis;
    
    private EzNoteFrameAbout winAbout;
    private EzNoteFrameAppearance winAppr;
    
    private EzNoteConfigurator conf;

    /**
     * Constructor and manual components init
     */
    public EzNoteFrame(EzNoteConfigurator conf) {
        initComponents();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text Files", "txt", "text");
        this.fc = new EzNoteFileChooser(this, "test");
        this.fc.setFileFilter(filter);
        this.winAbout = new EzNoteFrameAbout(this);
        this.winAbout.dispose();
        this.winAppr = new EzNoteFrameAppearance(this);
        this.winAppr.dispose();
        this.util = new EzNoteFrameUtil(this);
        this.doc = new EzNoteDocument(this);
        this.wlis = new EzNoteWindowAdapter(this);
        this.conf = conf;
        
        this.addWindowListener(wlis);
    }

    /**
     * Set the document listener of the window
     * @param dc EzNoteDocumentListener
     */
    
    public void setDocumentListener(EzNoteDocument dc) {
        this.editor.getDocument().addDocumentListener(dc);
    }

    /**
     * Returns the frame utilities class
     * @return EzNoteFrameUtil
     */
    public EzNoteFrameUtil getUtilities() {
        return this.util;
    }
    
    public EzNoteConfigurator getConfigurator() {
        return this.conf;
    }

    /**
     * Returns the filechooser of the window
     * @return EzNoteFileChooser
     */
    public EzNoteFileChooser getFileChooser() {
        return this.fc;
    }

    /**
     * Returns the document of the window
     * @return EzNoteDocument
     */
    public EzNoteDocument getDocument() {
        return this.doc;
    }

    /**
     * Returns the filename of the current document
     * @return String filename of the current document
     */
    public String getFilename() {
        return this.doc.getFile().getName();
    }

    /**
     * Returns the Editor component
     * @return JTextArea of the main frame
     */
    public JTextArea getEditor() {
        return this.editor;
    }

    public void themeApply(EzNoteTheme theme){
        //toolbar 1
        this.toolbarMain.setBackground(theme.getToolbarColor().getColor());
        this.toolNew.setBackground(theme.getToolbarColor().getColor());
        this.toolQSave.setBackground(theme.getToolbarColor().getColor());
        this.toolSaveAs.setBackground(theme.getToolbarColor().getColor());
        this.toolOpen.setBackground(theme.getToolbarColor().getColor());
        //toolbar 2
        this.toolbarAbout.setBackground(theme.getToolbarColor().getColor());
        this.buttonEzNote.setBackground(theme.getToolbarColor().getColor());
        //editor
        this.editor.setBackground(theme.getEditorColor().getColor());
        //font
        this.editor.setForeground(theme.getFontColor().getColor());
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jFileChooser1 = new javax.swing.JFileChooser();
        editorPane = new javax.swing.JScrollPane();
        editor = new javax.swing.JTextArea();
        toolbarMain = new javax.swing.JToolBar();
        toolNew = new javax.swing.JButton();
        sepr1 = new javax.swing.JToolBar.Separator();
        toolOpen = new javax.swing.JButton();
        toolQSave = new javax.swing.JButton();
        toolSaveAs = new javax.swing.JButton();
        sepr2 = new javax.swing.JToolBar.Separator();
        toolbarAbout = new javax.swing.JToolBar();
        buttonEzNote = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        buttonNew = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        buttonOpen = new javax.swing.JMenuItem();
        buttonQSave = new javax.swing.JMenuItem();
        buttonSaveAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        buttonExit = new javax.swing.JMenuItem();
        menuSettings = new javax.swing.JMenu();
        buttonAppearance = new javax.swing.JMenuItem();
        buttonSettings = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(540, 300));

        editor.setColumns(20);
        editor.setRows(5);
        editorPane.setViewportView(editor);

        toolbarMain.setBackground(new java.awt.Color(204, 204, 204));
        toolbarMain.setBorder(null);
        toolbarMain.setFloatable(false);
        toolbarMain.setForeground(new java.awt.Color(0, 0, 0));
        toolbarMain.setBorderPainted(false);
        toolbarMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        toolbarMain.setMaximumSize(new java.awt.Dimension(1000000, 36));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, toolbarMain, org.jdesktop.beansbinding.ELProperty.create("${preferredSize}"), toolbarMain, org.jdesktop.beansbinding.BeanProperty.create("minimumSize"));
        bindingGroup.addBinding(binding);

        toolNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_newfile.png"))); // NOI18N
        toolNew.setToolTipText("New");
        toolNew.setBorderPainted(false);
        toolNew.setFocusable(false);
        toolNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolNew.setMaximumSize(new java.awt.Dimension(28, 28));
        toolNew.setMinimumSize(new java.awt.Dimension(28, 28));
        toolNew.setPreferredSize(new java.awt.Dimension(28, 28));
        toolNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolNewActionPerformed(evt);
            }
        });
        toolbarMain.add(toolNew);
        toolbarMain.add(sepr1);

        toolOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_openfile.png"))); // NOI18N
        toolOpen.setToolTipText("Open...");
        toolOpen.setBorderPainted(false);
        toolOpen.setFocusable(false);
        toolOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolOpen.setMaximumSize(new java.awt.Dimension(28, 28));
        toolOpen.setMinimumSize(new java.awt.Dimension(28, 28));
        toolOpen.setPreferredSize(new java.awt.Dimension(28, 28));
        toolOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolOpenActionPerformed(evt);
            }
        });
        toolbarMain.add(toolOpen);

        toolQSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_savefile.png"))); // NOI18N
        toolQSave.setToolTipText("Save");
        toolQSave.setBorderPainted(false);
        toolQSave.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_savefile_disabled.png"))); // NOI18N
        toolQSave.setEnabled(false);
        toolQSave.setFocusable(false);
        toolQSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolQSave.setMaximumSize(new java.awt.Dimension(28, 28));
        toolQSave.setMinimumSize(new java.awt.Dimension(28, 28));
        toolQSave.setPreferredSize(new java.awt.Dimension(28, 28));
        toolQSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolQSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolQSaveActionPerformed(evt);
            }
        });
        toolbarMain.add(toolQSave);

        toolSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_saveasfile.png"))); // NOI18N
        toolSaveAs.setToolTipText("Save As...");
        toolSaveAs.setBorderPainted(false);
        toolSaveAs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        toolSaveAs.setFocusable(false);
        toolSaveAs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolSaveAs.setMaximumSize(new java.awt.Dimension(28, 28));
        toolSaveAs.setMinimumSize(new java.awt.Dimension(28, 28));
        toolSaveAs.setPreferredSize(new java.awt.Dimension(28, 28));
        toolSaveAs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolSaveAsActionPerformed(evt);
            }
        });
        toolbarMain.add(toolSaveAs);
        toolbarMain.add(sepr2);

        toolbarAbout.setFloatable(false);
        toolbarAbout.setRollover(true);
        toolbarAbout.setBorderPainted(false);
        toolbarAbout.setFocusable(false);
        toolbarAbout.setMaximumSize(new java.awt.Dimension(63, 36));
        toolbarAbout.setMinimumSize(new java.awt.Dimension(63, 36));
        toolbarAbout.setPreferredSize(new java.awt.Dimension(100, 36));

        buttonEzNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_about.png"))); // NOI18N
        buttonEzNote.setToolTipText("About EzNote");
        buttonEzNote.setBorderPainted(false);
        buttonEzNote.setFocusable(false);
        buttonEzNote.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        buttonEzNote.setMaximumSize(new java.awt.Dimension(28, 28));
        buttonEzNote.setMinimumSize(new java.awt.Dimension(28, 28));
        buttonEzNote.setPreferredSize(new java.awt.Dimension(28, 28));
        buttonEzNote.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonEzNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEzNoteActionPerformed(evt);
            }
        });
        toolbarAbout.add(buttonEzNote);

        menuFile.setMnemonic('f');
        menuFile.setText("File");

        buttonNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        buttonNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_newfile.png"))); // NOI18N
        buttonNew.setText("New");
        buttonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewActionPerformed(evt);
            }
        });
        menuFile.add(buttonNew);
        menuFile.add(jSeparator2);

        buttonOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        buttonOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_openfile.png"))); // NOI18N
        buttonOpen.setText("Open");
        buttonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenActionPerformed(evt);
            }
        });
        menuFile.add(buttonOpen);

        buttonQSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        buttonQSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_savefile.png"))); // NOI18N
        buttonQSave.setText("Save");
        buttonQSave.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_savefile_disabled.png"))); // NOI18N
        buttonQSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQSaveActionPerformed(evt);
            }
        });
        menuFile.add(buttonQSave);

        buttonSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_saveasfile.png"))); // NOI18N
        buttonSaveAs.setText("Save As...");
        buttonSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveAsActionPerformed(evt);
            }
        });
        menuFile.add(buttonSaveAs);
        menuFile.add(jSeparator1);

        buttonExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        buttonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gdr/icons/m_exit.png"))); // NOI18N
        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        menuFile.add(buttonExit);

        menuBar.add(menuFile);

        menuSettings.setMnemonic('p');
        menuSettings.setText("Preferences");

        buttonAppearance.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        buttonAppearance.setText("Appearance");
        buttonAppearance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAppearanceActionPerformed(evt);
            }
        });
        menuSettings.add(buttonAppearance);

        buttonSettings.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        buttonSettings.setText("Settings...");
        menuSettings.add(buttonSettings);

        menuBar.add(menuSettings);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolbarAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(toolbarMain, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE))
            .addComponent(editorPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toolbarMain, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toolbarAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(editorPane, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveAsActionPerformed
        try {
            EzNoteChangeValidator.validateAction(this.doc, EzNoteChangeValidator.FILE_SAVEAS);
        } catch (BadValidationException ex) {
            ex.printStackTrace();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buttonSaveAsActionPerformed

    private void buttonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenActionPerformed
        try {
            EzNoteChangeValidator.validateAction(this.doc, EzNoteChangeValidator.FILE_OPEN);
        } catch (BadValidationException ex) {
            ex.printStackTrace();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buttonOpenActionPerformed

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
        boolean isValid = false;
        try {
            isValid = EzNoteChangeValidator.validateAction(this.doc, EzNoteChangeValidator.FILE_NEW);
        } catch (BadValidationException ex) {
            ex.printStackTrace();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
        if (isValid) {
            this.newFile();
        }
    }//GEN-LAST:event_buttonNewActionPerformed

    private void buttonQSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQSaveActionPerformed
        try {
            EzNoteChangeValidator.validateAction(this.doc, EzNoteChangeValidator.FILE_QSAVE);
        } catch (BadValidationException ex) {
            ex.printStackTrace();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
        this.saveFile();
    }//GEN-LAST:event_buttonQSaveActionPerformed

    private void toolNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolNewActionPerformed
        boolean isValid = false;
        try {
            isValid = EzNoteChangeValidator.validateAction(this.doc, EzNoteChangeValidator.FILE_NEW);
        } catch (BadValidationException ex) {
            ex.printStackTrace();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
        if (isValid) {
            this.newFile();
        }
    }//GEN-LAST:event_toolNewActionPerformed

    private void toolQSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolQSaveActionPerformed
        try {
            EzNoteChangeValidator.validateAction(doc, EzNoteChangeValidator.FILE_QSAVE);
        } catch (BadValidationException ex) {
            ex.printStackTrace();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_toolQSaveActionPerformed

    private void toolSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolSaveAsActionPerformed
        try {
            EzNoteChangeValidator.validateAction(this.doc, EzNoteChangeValidator.FILE_SAVEAS);
        } catch (BadValidationException ex) {
            ex.printStackTrace();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_toolSaveAsActionPerformed

    private void toolOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolOpenActionPerformed
        try {
            EzNoteChangeValidator.validateAction(this.doc, EzNoteChangeValidator.FILE_OPEN);
        } catch (BadValidationException ex) {
            ex.printStackTrace();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_toolOpenActionPerformed

    private void buttonEzNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEzNoteActionPerformed
        this.winAbout.setLocationRelativeTo(this);
        this.winAbout.setVisible(true);
    }//GEN-LAST:event_buttonEzNoteActionPerformed

    private void buttonAppearanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAppearanceActionPerformed
        this.winAppr.setLocationRelativeTo(this);
        this.winAppr.setVisible(true);
    }//GEN-LAST:event_buttonAppearanceActionPerformed

    /**
     * Initialize a new file while the program is starting, and locks the quick
     * save buttons
     */
    public void initializeStartup() {
        this.newFile();
        this.disableSaveButtons();
    }

    /**
     * Enables save buttons
     * @deprecated Will not support disabled buttons anymore
     */
    @Deprecated
    public void enableSaveButtons() {
        this.buttonQSave.setEnabled(true);
        this.toolQSave.setEnabled(true);
    }

    /**
     * Disables save buttons
     * @deprecated Will not support disabled buttons anymore
     */
    @Deprecated
    public void disableSaveButtons() {
        this.buttonQSave.setEnabled(false);
        this.toolQSave.setEnabled(false);
    }

    ////ACTIONS
    private void newFile() {
        this.editor.setText("");
        this.setTitle(this.util.getWindowTitle(false, "Untitled"));
        this.doc.resetIndicators();
    }

    private void openFile() throws FileNotFoundException {
        this.doc.open();
    }

    private void saveFile() {
        this.doc.saveQ();
    }

    private void saveAsFile() {
        this.doc.saveAs();
    }
    //////


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem buttonAppearance;
    private javax.swing.JMenuItem buttonExit;
    private javax.swing.JButton buttonEzNote;
    private javax.swing.JMenuItem buttonNew;
    private javax.swing.JMenuItem buttonOpen;
    private javax.swing.JMenuItem buttonQSave;
    private javax.swing.JMenuItem buttonSaveAs;
    private javax.swing.JMenuItem buttonSettings;
    private javax.swing.JTextArea editor;
    private javax.swing.JScrollPane editorPane;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuSettings;
    private javax.swing.JToolBar.Separator sepr1;
    private javax.swing.JToolBar.Separator sepr2;
    private javax.swing.JButton toolNew;
    private javax.swing.JButton toolOpen;
    private javax.swing.JButton toolQSave;
    private javax.swing.JButton toolSaveAs;
    private javax.swing.JToolBar toolbarAbout;
    private javax.swing.JToolBar toolbarMain;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
